### ISSUE TITLE
Panic while expanding cluster

### ISSUE THREAD

**Issue by saimeCS** [CS-SI/SafeScale#67]
Expand cluster with 2 nodes with command: 'safescale cluster expand demo -n 2'
b''
b'panic: interface conversion: interface is nil, not error\n\ngoroutine 1 [running]:\ngithub.com/CS-SI/SafeScale/safescale/server/cluster/control.(*Controller).AddNodes(0xc000160780, 0x14c24a0, 0xc00038e000, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/stephan/go/src/github.com/CS-SI/SafeScale/safescale/server/cluster/control/controller.go:559 +0xdb7\ngithub.com/CS-SI/SafeScale/safescale/cli/safescale/cmd.glob..func20(0xc0000d2420, 0xc0000d2420, 0x12bcabf)\n\t/home/stephan/go/src/github.com/CS-SI/SafeScale/safescale/cli/safescale/cmd/cluster.go:663 +0x3ae\ngithub.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.HandleAction(0x1153220, 0x13293c8, 0xc0000d2420, 0xc000030100, 0x0)\n\t/home/stephan/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/app.go:490 +0xfe\ngithub.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.Command.Run(0x12be6d8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12ca0ec, 0x12, 0x0, ...)\n\t/home/stephan/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/command.go:210 +0xcdf\ngithub.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001a1520, 0xc0000d2000, 0x0, 0x0)\n\t/home/stephan/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/app.go:379 +0xd44\ngithub.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.Command.startApp(0x12bf9a7, 0x7, 0x0, 0x0, 0x1cc6940, 0x2, 0x2, 0x12d0cd9, 0x19, 0x0, ...)\n\t/home/stephan/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/command.go:298 +0x119a\ngithub.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.Command.Run(0x12bf9a7, 0x7, 0x0, 0x0, 0x1cc6940, 0x2, 0x2, 0x12d0cd9, 0x19, 0x0, ...)\n\t/home/stephan/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/command.go:98 +0x17c3\ngithub.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.(*App).Run(0xc0001a1380, 0xc0000c2120, 0x6, 0x6, 0x0, 0x0)\n\t/home/stephan/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/app.go:255 +0xa64\nmain.main()\n\t/home/stephan/go/src/github.com/CS-SI/SafeScale/safescale/cli/safescale/main.go:145 +0x16f3\n'

**Comment by saimeCS** [comment]
Fixed in commit #2c10eb8
