### ISSUE TITLE
safescale platform expand fails with panic

### ISSUE THREAD

**Issue by vplanche-cssi** [CS-SI/SafeScale#77]
panic: interface conversion: interface {} is nil, not bool

goroutine 109 [running]:
github.com/CS-SI/SafeScale/lib/server/cluster/control.(*foreman).taskCreateNode(0xc0004f8b40, 0x1cf7aa0, 0xc0006e05a0, 0x1886e00, 0xc0002747e0, 0x0, 0x0, 0x0, 0x0)
    /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/server/cluster/control/foreman.go:1738 +0x1845
github.com/CS-SI/SafeScale/lib/server/cluster/control.(*foreman).taskCreateNode-fm(0x1cf7aa0, 0xc0006e05a0, 0x1886e00, 0xc0002747e0, 0xc000382fb8, 0xdf6d85, 0xc000529110, 0xc00022e800)
    /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/server/cluster/control/controller.go:731 +0x77
github.com/CS-SI/SafeScale/lib/utils/concurrency.(*task).run(0xc0006e05a0, 0xc0004c48c0, 0x1886e00, 0xc0002747e0)
    /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/utils/concurrency/task.go:276 +0x6b
created by github.com/CS-SI/SafeScale/lib/utils/concurrency.(*task).controller
    /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/utils/concurrency/task.go:242 +0x8f

**Comment by vplanche-cssi** [comment]
- Fixed by commit c95f0889f794d32b6242980bdf7e72b6debc2631
- Added missing parameter validation
